name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to branches matching v*, e.g., v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest # GitHub Actions runs on Linux by default

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a recent LTS version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Create .mcaddon
      run: npm run mcaddon

    - name: Get release version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          # Release ${{ steps.get_version.outputs.VERSION }}

          This release includes the latest changes and the compiled add-on.
        files: dist/packages/*.mcaddon # Attach the .mcaddon file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
